/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '产品概述',
    },
    {
      type: 'category',
      label: '产品介绍',
      link: {
        type: 'doc',
        id: 'product/index'
      },
      collapsed: true,
      items: [
            'product/what-is-zyyq',
            'product/features',
        'product/advantages',
        'product/concepts',
        'product/architecture'
      ]
    },
    {
      type: 'category',
      label: '控制台',
      link: {
        type: 'doc',
        id: 'console/index',
      },
      collapsed: true,
      items: [
        'console/index',
        'console/getting-started',
        'console/product-management',
        'console/app-management',
        'console/device-management',
        'console/monitoring',
        'console/user-account'
      ],
    },
    {
      type: 'category',
      label: '设备开发',
      collapsed: true,
      items: [
        'device/device-sdk',
      ],
    },
    {
      type: 'category',
      label: 'App开发',
      collapsed: true,
      items: [
        'app/android-app-sdk',
        'app/ios-app-sdk',
      ],
    },
    {
      type: 'category',
      label: 'PC开发',
      collapsed: true,
      items: [
        'pc/windows-pc-sdk',
      ],
    },
    {
      type: 'category',
      label: 'Web开发',
      collapsed: true,
      items: [
        'web/web-sdk',
      ],
    },
    {
      type: 'category',
      label: '云端API',
      collapsed: true,
      items: [
        'api/api-overview',
        'api/error-code-dictionary',
        'api/signature-mechanism',
        'api/api-interface',
      ],
    },
    {
      type: 'category',
      label: '开发参考',
      collapsed: true,
      items: [
        'development/index',
      ],
    },
    {
      type: 'category',
      label: '帮助中心',
      collapsed: true,
      items: [
        'help/account-development-issues',
      ],
    },
  ],
};

export default sidebars;
